version: "3.8"

networks:
  auth-network:
    name: auth-network
    driver: bridge

# list services
services:
  postgresdb:
    image: postgres:alpine
    container_name: postgresdb2
    restart: always
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    networks:
      - auth-network
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=root

  appauth:
    build: .
    ports:
      - target: 5005
        published: 5005
        protocol: tcp
        mode: host
    networks:
      - auth-network
    depends_on:
      - postgresdb