DROP DATABASE IF EXISTS userauth_db;

CREATE DATABASE userauth_db;

\c userauth_db;

CREATE TABLE "accounts" (
                            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "username" varchar(255) NOT NULL,
                            "password" varchar(255) NOT NULL
);

CREATE TABLE "users" (
                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "full_name" varchar(255) NOT NULL,
                         "address" varchar(255) NOT NULL,
                         "account_id" int NOT NULL
);

CREATE INDEX ON "accounts" ("username");

ALTER TABLE "users" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");
